---
title: "MARC Session Planning Form"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Leader Name: Jacob Green | Course: Welcome and goal setting |
|--------------------------|----------------------------------|
| Date created:9/11/2020 | Date implemented: 9/11/2020 |
| Week in course: 1 | Resources: None |

## Step 1: Meet with coordinators and discuss the following:
Useful resource; **"Identifying the Difficulties with Difficult Ideas"**

1. List the most important concepts and skill introduced in this topic
    a. Concepts
      * Getting back together after summer
      * Clarifying expectations and goals for this Fall
      * What is our new norm in meetings

    b. Skills
      * Open conversation around expectations from ourselves and each other
      * Clearly defining goals that are SMART for this Fall

2. Which concepts and skills can be the most challenging for researchers this week? Why?

I think having open and sincere conversation about what trainees expect out of the coordinating team and what the coordinating team expects from trainees is crucial. This begins with articulating the goals we have set for ourselves and each other. This allows all of us to visualize these goals and see how we may facilitate one another through this trying semester.

## Step 2: Plan your session based on who is attending in the lecture and meeting with the instructor
When planning your sessions remember to stay flexible with the actual implementation of your session plan. Trainees may come prepared with their own questions and agenda. Stay open to their requests. Useful handouts; **Bloom's Taxonomy, Learning Outcome ABC's, S.M.A.R.T, Strategy Du Jour.**

1. **Session Learning Objectives**
Describe what you would like to see your trainees be able to do by the end of your sessions? Use the list of concepts and skills you identified in Step #1. 

1) I would like to see them clearly articulate their expectations of the program and the goals that they have set for themselves

2. **Check-in**
Allow for a 10-20 minute period where trainees are able to communicate with coordinators and each other about the weeks goals, trials, and tribulations.

Get everyone into the zoom call, have banter and catch up time, give updates from our labs and summer activities

3. **Warm-up**
Describe a 10-15 minute opportunity that will help trainees to organize, prioritize, define, identify, label, list, record, or review, ideas.

Confident

Curious

Confused

Concerned

4. **Most of the session time**
Describe how you will utilize the meeting activity (50-60 minutes) to help trainees achieve the learning objectives you have developed.

Discuss goals of trainees

Discuss goals of coordinators

Discuss expectations of trainees

Discuss expectations of coordinators

5. **Wrap-up**
Describe a 10-15 minute closing opportunity that will help trainees summarize their work in today's session. 

How are we going to hold ourselves and each other accountable this semester?

5 minutes to write your thoughts on what is going to make you successful this semester. 

## Step 3: Reflect on this week's session
Once you have hosted the session and completed the reflection share your completed session plan with your coordinators and review all of the activites from that week.

**1. What worked in the session? What was successful?**

**2. What did trainees learn? How do you know?**

**3. What would you change about your session today?**

**4. What specific content areas and study strategies did you recommend that trainees pursue before next week's sessions?**

**5. What are you considering as good use of next week's session?**

